### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by HaoZeke** [svenevs/exhale#93]
I'm working through the basic installation instructions and am hitting the following error:

```bash
[~] Exhale: parsing Doxygen XML.

(!) Exception caught while parsing:Traceback (most recent call last):
  File "/home/haozeke/.cache/pypoetry/virtualenvs/symengine.github.io-YsynZpqj-py3.8/lib/python3.8/site-packages/exhale/deploy.py", line 394, in explode
    textRoot.parse()
  File "/home/haozeke/.cache/pypoetry/virtualenvs/symengine.github.io-YsynZpqj-py3.8/lib/python3.8/site-packages/exhale/graph.py", line 1061, in parse
    self.parseFunctionSignatures()
  File "/home/haozeke/.cache/pypoetry/virtualenvs/symengine.github.io-YsynZpqj-py3.8/lib/python3.8/site-packages/exhale/graph.py", line 2002, in parseFunctionSignatures
    parameters.append(param.type.text)
AttributeError: 'NoneType' object has no attribute 'text'
make: *** [Makefile:20: html] Error 1
```

This is with the following `config.py`:

```python
# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Symengine'
copyright = '2020, Symengine Development Team'
author = 'Symengine Development Team'

# The full version, including alpha/beta/rc tags
release = '0.1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'breathe',
    'exhale'
]

# Setup the breathe extension
breathe_projects = {
    "Symengine": "./doxyoutput/xml"
}
breathe_default_project = "Symengine"

# Setup the exhale extension
exhale_args = {
    # These arguments are required
    "containmentFolder":     "./api",
    "rootFileName":          "library_root.rst",
    "rootFileTitle":         "Library API",
    "doxygenStripFromPath":  "..",
    # Suggested optional arguments
    "createTreeView":        True,
    # TIP: if using the sphinx-bootstrap-theme, you need
    # "treeViewIsBootstrap": True,
    "exhaleExecutesDoxygen": True,
    "exhaleDoxygenStdin":    "INPUT = ../include"
}

# Tell sphinx what the primary language being documented is.
primary_domain = 'cpp'

# Tell sphinx what the pygments highlight language should be.
highlight_language = 'cpp'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
```

The paths do have the content required.

**Comment by svenevs** [comment]
Oh my what a useless error!

https://github.com/symengine/symengine

Is this your project? Can you push a branch so that I can clone and diagnose?

**Comment by HaoZeke** [comment]
Hi @svenevs! Thanks for the prompt response. I [set up this branch to reproduce the error](https://github.com/symengine/symengine.github.io/tree/exhaleBug).

**Comment by HaoZeke** [comment]
Surprisingly that just worked. o.O must have had a bad clean step.

**Comment by Aakash-kaushik** [comment]
Hey I am facing the same issue, though i don't have a exact same copy but this is rather on a bigger project.
